version: "2"
services:
  postgres:
    image: postgres
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ppdli
  ptmMaster:
    image: jvsoest/ptm_master
    volumes:
      - ./config.json:/app/config.json
    links:
      - postgres:dbhost
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
